### PR TITLE
Add missing links, make memory usage more readable

### PR DESCRIPTION
**Pull request by Globegitter**
Just a few minor changes that make imo everything a little bit nicer.
- I did not know what `rss` meant, so renamed to residentSetSize to make that more clear for people with little experience in that area.
- Added conversion to human readable memory sizes
- Don't load whole lodash, since only two functions are needed
- Improved warning message a bit

### CODE REVIEW

**Comment by mikermcneil** [comment]
@Globegitter thanks man!

**Comment by mikermcneil** [comment]
@Globegitter i totally did that thing where I started changing code without looking for pull requests first-- would you mind rebasing if you get around to it before me?  I'll wait before publishing a new npm vers

PS- I also didn't know what rss meant, thanks :)

**Comment by Globegitter** [comment]
@mikermcneil Ha, I know that feeling no worries. Fixed. Btw, cool that you are adding a request logger - used my own so far. I'll probably add one or two things from there so that can be replaced.

**Comment by Globegitter** [comment]
Ah sorry, forgot one thing - give me a minute.

**Comment by Globegitter** [comment]
@mikermcneil Just put the modifications in this PR. Let me know if that's alright with you. Just showing now the statuscode as well as the size of the response body and I added a possibility to turn logging off even in the dev environment, by setting the keys to 'never'.

**Comment by mikermcneil** [comment]
@Globegitter awesome looks great :)

**Comment by mikermcneil** [comment]
@Globegitter thought: we could potentially call out to https://github.com/mikermcneil/sails-hook-apianalytics instead (had that code laying around)

published 1.0.0 on npm

**Comment by Globegitter** [comment]
Awesome @mikermcneil . Yeah I just hooked it into my current project and will give it a spin to see what exactly it logs etc.

**Pull request merged**
